version: '3'

services:
  app:
    build:
      context: ./docker/php-fpm
    volumes:
      - ~/.ssh:/home/${USER}/.ssh:rw
      - ./:/var/www
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/



volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
